version: '3.10'

services:
    clickhouse:
        container_name: clickhouse-database
        image: clickhouse/clickhouse-server
        ports:
            - "8123:8123"
        env_file:
            - .env
        volumes:
            - ./clickhouse/users.d/:/etc/clickhouse-server/users.d/
            - ./clickhouse/data/:/var/lib/clickhouse/data
            - ./clickhouse/user_defined/:/var/lib/clickhouse/user_defined
            - ./clickhouse/init:/docker-entrypoint-initdb.d
        networks:
            - minenet

    postgres:
        container_name: airflow-postgres
        image: postgres:13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U airflow" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - minenet

    scheduler:
        container_name: airflow-scheduler
        image: apache/airflow:2.5.0-python3.9
        entrypoint: /opt/airflow/scripts/entrypoint.sh
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        networks:
            - minenet
        volumes:
            - ./airflow:/opt/airflow

    webserver:
        container_name: airflow-webserver
        image: apache/airflow:2.5.0-python3.9
        command: webserver
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./airflow:/opt/airflow
        networks:
            - minenet
        ports:
            - "8080:8080"

networks:
    minenet:
        driver: bridge
